name: Virtually Digital
favicon: null
layout_spectrum: 0.4554089780431241
typography_spectrum: 0.9858853404875845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.36790311336517334
  lightness: 0.317198023898527
  saturation: 0.9368226958904415
  rhythmicContrast: 0.8320441460236907
purpose: []
